version: "3.8"

services:

  ai:
    container_name: flute_ai
    build:
      context: ./clusters/ai
    command:
      - bash -c "python3 main:py"

  api:
    container_name: flute_api
    build:
      context: ./clusters/api
    command: bash -c "python3 -m uvicorn main:app --host 0.0.0.0 --port 8000"
    environment:
      - JWT_SECRET_KEY=${JWT_SECRET_KEY}
    ports:
      - "${API_PORT}:8000"
    depends_on:
      - ai
      - auth
      - database
      - redis

  auth:
    container_name: flute_auth
    build:
      context: ./clusters/auth
    command:
      - bash -c "python3 main:py"


  database:
    container_name: flute_db_surreal
    entrypoint: /surreal start --user ${DB_USER} --pass ${DB_PASS}
    image: surrealdb/surrealdb:latest
    ports:
      - "${DB_PORT}:8000"

  redis:
    image: redis:alpine
    container_name: flute_redis
    ports:
      - "6379:6379"
    command: redis-server --save 20 1 --loglevel warning --requirepass ${REDIS_KEY}

  nginx:
    image: nginx:1-alpine
    container_name: nginx
    ports:
      - "8089:80"


  web:
    container_name: flute_web
    command: bash -c "trunk serve --address 0.0.0.0 --port 8000"
    build:
      context: ./clusters/web
    ports:
      - "${WEB_PORT}:8000"
    depends_on:
      - api
